version: "3.8"

services:

  auth-service:
    build: ./services/auth-service
    container_name: calmroot-auth
    restart: unless-stopped
    environment:
      PORT: 3001
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-your-email@gmail.com}
      SMTP_PASS: ${SMTP_PASS:-YOUR_GMAIL_APP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM:-your-email@gmail.com}
    networks:
      - calmroot-net
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s

  assessment-service:
    build: ./services/assessment-service
    container_name: calmroot-assessment
    restart: unless-stopped
    environment:
      PORT: 3002
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_URL: http://auth-service:3001
      RUN_SEED: "true"
    depends_on:
      auth-service:
        condition: service_healthy
    networks:
      - calmroot-net
    ports:
      - "3002:3002"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s

  therapist-service:
    build: ./services/therapist-service
    container_name: calmroot-therapist
    restart: unless-stopped
    environment:
      PORT: 3003
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_URL: http://auth-service:3001
      ASSESSMENT_SERVICE_URL: http://assessment-service:3002
    depends_on:
      auth-service:
        condition: service_healthy
      assessment-service:
        condition: service_healthy
    networks:
      - calmroot-net
    ports:
      - "3003:3003"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3003/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./services/frontend
      args:
        VITE_AUTH_URL: http://localhost:3001
        VITE_ASSESSMENT_URL: http://localhost:3002
        VITE_THERAPIST_URL: http://localhost:3003
    container_name: calmroot-frontend
    restart: unless-stopped
    depends_on:
      - auth-service
      - assessment-service
      - therapist-service
    networks:
      - calmroot-net
    ports:
      - "80:80"
    healthcheck:
      disable: true
#      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 10s

networks:
  calmroot-net:
    driver: bridge

